export const keywords = [
  "Next.js",
  "React",
  "Node.js",
  "TypeScript",
  "JavaScript",
  "Tailwind CSS",
  "React Hooks",
  "Context API",
  "SPA",
  "PWA",
  "Mobile First",
  "SEO",
  "HTML5",
  "CSS3",
  "SCSS",
  "Framer Motion",
  "Shadcn UI",
  "Express",
  "Prisma",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "Supabase",
  "REST API",
  "Docker",
  "Git",
  "GitHub",
  "Linux",
  "Clean Code",
  "Portfólio",
  "Desenvolvedor Fullstack",
  "Desenvolvedor Frontend",
  "Desenvolvedor Backend",
  "Desenvolvedor Júnior",
  "Programador",
  "Paulo Victor",
  "Fullstack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Junior Developer",
  "Software Engineer",
  "Web Developer",
];
